### ISSUE TITLE
org-font-lock-ensure is deprecated

### ISSUE THREAD

**Issue by trev-dev** [amno1/org-view-mode#11]
For reference: https://github.com/org-roam/org-roam/issues/2235

On my current install, org-font-lock-ensure doesn't even exist, so this package will not work.  Will we support backward-compatibility for emacs < 26?  The necessary corner case will need to be taken into consideration if the answer is "yes".  Otherwise, we should replace `org-font-lock-ensure` with `font-lock-ensure`

**Comment by amno1** [comment]
I don't think it is interested to support Emacs < 26. Honestly, no :), but replacing org-font-lock-ensure with font-lock-ensure is perfectly fine. It is just an alias for font-lock-ensure in the current master anyway. Font-lock-ensure is available since 25.1
