### ISSUE TITLE
Adding a "org-view-reading-font-mode"

### ISSUE THREAD

**Issue by trev-dev** [amno1/org-view-mode#3]
I'd like to contribute an optional "reading font mode" to compliment this minor mode and wanted to brainstorm a bit about what this could look like.

I was thinking of the following:
1. A toggle variable so that this feature could be easily customized off: `org-view-reading-font-enable`
2. A customizable variable for which font to use: `org-view-reading-font-family`
3. A customizable font-size per face fields list with default settings. This way one could customize which headings get what size and what the paragraph sizes would be: `org-view-reading-font-sizes`
4. A couple of pre-installed, open source fonts that are intended for readability. One sans-serif, the other would be serif. Not sure which fonts these would be yet.

Thoughts?

**Comment by amno1** [comment]
Principally, I am not against. I do see the amount of work needed to implement a separate theme as substantial. Org-mode is big, like huge. If one would to implement a reading theme, it would generally mean to theme the entire org-mode. Maybe it is enough to do just outlines and major text features, I don't know, maybe I am wrong, just my initial thought. I am also thinking that many people use custom themes, which often times theme org mode too. 

Otherwise, if you are interesting to implement something like that, I would suggest creating an org-view-theme as a minor mode? That way, when org-mode has styled the file, the org-view-theme would overwrite that styling. A minor mode also works as a toggle, so it is an optional feature by default. To be honest, I am not really expert at theming and faces. What do you think yourself?

**Comment by andersjohansson** [comment]
Just saw this and wanted to point out that `face-remap` would be the way to go for things like this.

In my config I have a small (quite idiosyncratic) library for this.
https://github.com/andersjohansson/.emacs.d/blob/main/lisp/doc-font.el

Heavily inspired by the package mixed-pitch (https://gitlab.com/jabranham/mixed-pitch).
But also with some inspiration from here: https://lepisma.github.io/2017/10/28/ricing-org-mode/

**Comment by amno1** [comment]
> Just saw this and wanted to point out that face-remap would be the way to go for things like this.

Thank you, that is probably the correct way to implement this.

However, what I meant is that I would prefer theming functionality to be contained in a minor mode, just so people can choose if they wish to use it or not. 

My reasoning is that some Emacs themes already have org mode themed, so people might be used to their theme. Switching to another theme might be visually distracting, so I would prefer, by default, to keep the original look of the org buffer, whatever user have. But I am not against including a theme in the form of a bunch of faces or maybe some included settings to be used as a theme, so users can just switch them on or off. Also, those settings should probably be applied as overlays, so they don't change the appearance of other org buffers, and they should be switched off when the user exits org-view-mode.

At least, I think it would be a good way to implement it. I don't know what is the status on per-buffer or per-mode theming, I haven't looked so much at it to be honest. Potentially, that would be something to look at if someone is interested to implement theming for reading only.

**Comment by andersjohansson** [comment]
Yes, the point with face-remapping is that it allows you to do a quite selective remapping of faces only in the current buffer. Easy to create a minor mode that can be toggled on and off to achieve the effect of for example a nice serif font (as I do in the `doc-font-mode` defined in my library, even if that has some additional bells and whistles).

**Comment by andersjohansson** [comment]
By the way, I am not suggesting you should do either way for `org-view-mode`. I am not currently using it and wanted to be helpful if either you or @trev-dev wanted to do something like this, either in `org-view-mode` or separately :smile:.

**Comment by amno1** [comment]
Sounds great, thank you. 

Yes, I took a quick look when I saw your first message. Will check it more later, and the other links you have posted too.

**Comment by trev-dev** [comment]
Stale

**Comment by amno1** [comment]
I totally forgot this myself; @trev-dev, are you still interested to have this? I have looked at the Anders examples; if you have example code based on font remapping or do you have a patch branch with your suggestions so we can test, I am probably ok to included it.

**Comment by trev-dev** [comment]
If the interest is still there, I am happy to help finish what I started.  When I last dabbled in Emacs I had a toggle function that adjusted my font on demand.  It's simple and should be straight forward to adapt.

**Comment by amno1** [comment]
Thank you for the implementing this trev-dev!
