### ISSUE TITLE
Feature Request: hide SCHEDULED and DEADLINE

### ISSUE THREAD

**Issue by molok** [amno1/org-view-mode#4]
they are often used by `org-agenda`, see https://orgmode.org/manual/Deadlines-and-Scheduling.html

**Comment by amno1** [comment]
I don't think this mode is well-suited to use in agenda to begin with, but sure, it isn't hard to do in the same style as other stuff.

**Comment by amno1** [comment]
Can you (or someone else) provide a few suitable test files?

By the way, it is not expected to work in agenda views, just in plain org file?

**Comment by molok** [comment]
it's an org-mode native feature, you can schedule or set a timeline (or both!) on any headline, it is used in plain org files. You can set it using the `org-deadline` and `org-schedule` interactive functions. it looks like this.


    * main heading
    ** heading 1
    DEADLINE: <2022-02-18 ven>
    content 1
    ** heading 2
    SCHEDULED: <2022-02-18 ven>
    content 2
    ** heading 3
    SCHEDULED: <2022-03-19 sab> DEADLINE: <2022-02-18 ven>
    content 3
    ** heading 4
    DEADLINE: <2022-03-19 sab> SCHEDULED: <2022-02-18 ven>
    content 4
    ** heading 5
    content 5

**Comment by amno1** [comment]
I can do such simple tests myself, but I prefer to test on some real-life file, "just in case". But  I guess this is so simple thing, so there are no additional stuff people can put there?

It is now in the master, commit: f9cdcd9fd89218de19fd51ae0957c229ccc53c76.  I have squashed some unnecessary commits together with this one, so it looks a bit more than it is.

Let me know if there are problems.
