### ISSUE TITLE
Feature Request: hide ellipsis

### ISSUE THREAD

**Issue by molok** [amno1/org-view-mode#5]
when a drawer is collapsed the `org-ellipsis` string is shown instead.

![image](https://user-images.githubusercontent.com/34475/154361661-4b289faf-94fd-4cf6-b30e-6d18200e8072.png)

![image](https://user-images.githubusercontent.com/34475/154361311-8a540f92-77ab-4b83-8200-1aa01471f18e.png)

enabling `org-view-mode` when the drawer is collapsed will still show the ellipsis

![image](https://user-images.githubusercontent.com/34475/154361477-6b72f13f-4186-4898-8fa4-1fd44c1be20b.png)

this does not happen if `org-view-mode` is enabled when the drawer is expanded

![image](https://user-images.githubusercontent.com/34475/154361588-43a2f744-884c-4799-a738-f40236aad992.png)

**Comment by amno1** [comment]
Ok, I'll put it on a wish list, but I don't promise. Yes, ellipsis are implemented as a text property or overlay, so that is why they don't disappear. I'll see when I have time what I can do.

**Comment by amno1** [comment]
Implemented in a 'hackish' way: dbf9a21054cae18a14307c2f9096a4461f108021.

If someone has better idea, PR or a patch would be appreciated.
