### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by Ypot** [amno1/org-view-mode#7]
If I try:
`package-install-file org-view-mode.el`

I receive:
`package-buffer-info: Package lacks a file header`

If I try:
` (require 'org-view-mode)`

Then:
`load-with-code-conversion: Symbol’s value as variable is void: <!DOCTYPE`

**Comment by amno1** [comment]
> package-buffer-info: Package lacks a file header

This is the package header - I have just copied it from the [org-view-mode.el](https://github.com/amno1/org-view-mode/blob/main/org-view-mode.el):

`;;; org-view-mode.el --- Read-only viewer with less markup clutter in org mode files  -*- lexical-binding: t; -*-`

And I think this belongs to it as well:

```
;; Author: Arthur Miller
;; Version: 1.0.0
;; Keywords: tools convenience
;; Package-Requires: ((emacs "25.1"))
;; URL: https://github.com/amno1/org-view-mode
```

I have also just tested package-install-file and it worked just fine, you can see here messages from my *Messages* buffer:

```
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations [2 times]
Package ‘org-view-mode-1.0.0’ deleted.
  INFO     Scraping files for org-view-mode-autoloads.el... 
Generating autoloads for org-view-mode.el...done
  INFO     Scraping files for org-view-mode-autoloads.el...done
Wrote /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0/org-view-mode-autoloads.el [2 times]
Checking /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0... [3 times]
Compiling /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0/org-view-mode.el...done
Wrote /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0/org-view-mode.elc
Checking /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0...
Done (Total of 1 file compiled, 2 skipped)
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
You can run the command ‘package-install-file’ with M-x p-i-fi RET
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
scroll-up-command: End of buffer
```

And here is the content in the package-user-dir (elpa) where it is installed:

 ```
 /home/arthur/.emacs.d/elpa/org-view-mode-1.0.0:
  drwxr-xr-x   2 arthur users  4096 18 feb 15.02 .
  drwxr-xr-x 273 arthur users 20480 18 feb 15.02 ..
  -rw-r--r--   1 arthur users  1240 18 feb 15.02 org-view-mode-autoloads.el
  -rw-r--r--   1 arthur users 24808 18 feb 15.02 org-view-mode.el
  -rw-r--r--   1 arthur users 22105 18 feb 15.02 org-view-mode.elc
  -rw-r--r--   1 arthur users   412 18 feb 15.02 org-view-mode-pkg.el

```

> load-with-code-conversion: Symbol’s value as variable is void: <!DOCTYPE

That looks like a first token in HTML5 file. How did you download org-view-mode.el?

If you are saving it through the browser, via save button, then you have probably saved "html-ized" version that GitHub serves to browsers. What you want is to press on that "Raw" button file to get raw text version. Even better you can clone the repository. From command prompt:

git clone https://github.com/amno1/org-view-mode

When you have cloned it open the directory in Emacs, and just M-x package-install-file RET. 

You can also wait for a few days, I have submitted the package to the Melpa, just waiting for their approval. But as soon as they accept it you will be able to install it via package-install, or use package. Alternatively, you can also use [Straight](https://github.com/raxod502/straight.el), there is an instruction in the README file.

**Comment by Ypot** [comment]
Thanks, Arthur.
You're right, I was downloading the file using "right click - save link as..." :facepalm:

I've been tweaking my init for hours this week to get some text not too ugly to read, so I couldn't wait to see your work. I see you've worked mainly on Blocks, Quotes look nice!!
Properties Block seems to dissapear, but the symbol to unfold it, remains.

I would love some "typewriting" too for normal paragraphs. I haven't got very far (org-view-mode 1):

![Sin nombre](https://user-images.githubusercontent.com/30699014/154760117-007eb9c1-1aeb-46ec-9058-6df43ebc4165.png)

**Comment by amno1** [comment]
I am glad you solved the problem about the installation.

> Quotes look nice!!

Thanks!

> Properties Block seems to dissapear, but the symbol to unfold it, remains.

You mean ellipses that denote the hidden text? Seems to me like you are using some different character than ellipses, perhaps a Unicode character?

I have just uploaded a little option to hide ellipses, but it comes with a big caveat: it hides all ellipses, so you won't be able to see if there is more text or not, so use it at your own risk.

If I understand your picture, you would like all your paragraphs to look like quotes? However, your paragraphs that you have marked as quotes, does not look like produced by my code?
I am not sure if I understand your picture correctly. 

Anyway, you could roll your own. The real work would be to construct a proper regex to recognize your paragraphs. Problem here is not to find paragraphs, but to sort out the stuff that does not count as paragraphs. But once you can recognize what is a paragraph, and have end points of a paragraph, you can call (org-view--prettify-quote beg end prettify) to make the region between beg and end look like a quote. Prettify is a boolean flag that means to perform quote styling or to remove it. Typically you would put it in a loop as you can see how it is done with leading stars, properties, etc.

**Comment by Ypot** [comment]
Yes, I changed the default ellipses. Thanks for the new option :)

The paragraphs marked as QUOTES are affected by your code (block "quote" is hidden) but i don't know why it is not in italics, maybe because of my face and fonts settings?

I don't really want the "normal paragraph" to look like quotes, but the idea of them looking like a book, with a quality near to typographical, is appealing. I just wanted to show that I tried to make my reading more pleasant by making the paragraphs narrower and the first line indented; it looks more pathetic than professional, but it's a start for me xD

Best regards

**Comment by amno1** [comment]
> The paragraphs marked as QUOTES are affected by your code (block "quote" is hidden) but i don't know why it is not in italics, maybe because of my face and fonts settings?

I don't know, it could be. You can set your own font. I have chosen italics just so I can show some difference, but I really assume that most people would customize it to something more distinguished.

> I don't really want the "normal paragraph" to look like quotes, but the idea of them looking like a book, with a quality near to typographical, is appealing. I just wanted to show that I tried to make my reading more pleasant by making the paragraphs narrower and the first line indented; it looks more pathetic than professional, but it's a start for me xD

Ah, forgive me, my thoughts were elsewhere. I see now. No, I don't think it's pathetic, it looks nice. I am not sure if I personally am the biggest fan of serif fonts in general,  but I do understand it is the old typewriter-looking font. How do you indent paragraphs? Manually, or do you have some mode that does it for you? 

> The idea of them looking like a book, with a quality near to typographical, is appealing. 

Yepp, I completely agree with you on that one.

**Comment by Ypot** [comment]
To indent the first lines, I discovered little time ago (after a lot of poor Google results) the package adaptive-wrap, it's on MELPA. A bless, I was already thinking it would need hard indentation, but that package solved it.

**Comment by amno1** [comment]
Thank you, didn't know about that one, I'll check it out.
