### ISSUE TITLE
Quote blocks face don't seem to be affected by org-view

### ISSUE THREAD

**Issue by Ypot** [amno1/org-view-mode#8]
As I showed you yesterday, my quote blocks don't get the "italics". Could it be because I have in my settings this?:
`(org-fontify-quote-and-verse-blocks 1) `

Or could it be because my quote face can't be italized?
![Sin nombre](https://user-images.githubusercontent.com/30699014/154800071-ab578e2f-9949-4696-9797-ce5e1ef6f7d6.png)

**Comment by amno1** [comment]
org-view-mode uses overlays to fontify text over whatever org does. Overlays take precedence over text propreties so you should see what you have defined in org-view-quote-face. What I see in your screenshot is that you haven't set your option. You should probably set your option and restart org-view-mode.
