### ISSUE TITLE
Accessible screencast

### ISSUE THREAD

**Issue by pmeckoni** [amno1/org-view-mode#9]
Many developers put a screencast / screenshot to help others understand what to expect. 
If that is what is intended in the screencast file, I urge you to consider accessibility by improving the contrast.
The best way to do it is to use a white background with darker text. It will help in improved readability of the screencast.

**Comment by amno1** [comment]
Maybe the bigger problem here is that the resolution is quite high, and when it gets scaled down it does not look very well?

> The best way to do it is to use a white background with darker text. It will help in improved readability of the screencast.

It is not so much to read here, It just shows some markup hidden and displayed. But if I re-record it, I will certainly think of what you say. Thank you for the input.
